---
rules:
  ## Stylistic ##
  indent:
    - 1
    - 4
    - SwitchCase: 1
      VariableDeclarator:
        var: 2
  linebreak-style:
    - 2
    - unix
  semi:
    - 1
    - never
    - beforeStatementContinuationChars: always
  comma-dangle:
    - error
    - always-multiline
  space-before-function-paren:
    - 1
    - anonymous: always
      named: never
  consistent-this:
    - 1
    - self
  ## Semantic ##
  no-invalid-this: 2  # prevent gotcha: closures inside methods don't inherit 'this'
  no-shadow:
    - 2
    - builtinGlobals: true
  no-shadow-restricted-names: 2
  no-unexpected-multiline: 2
  no-unused-vars:
    - 2
    - args: none
  strict:
    - 2
    - global
env:
  es6: true
  es2017: true
  commonjs: true
extends: eslint:recommended
